fe: fe.o fesub.o fe1.o fezoom.o fewin.o feshow.o feprint.o
	     cc fe.o fesub.o fe1.o fezoom.o fewin.o feshow.o feprint.o -n -o fe
fe1.o: fe1.c fedef.h
	cc -c fe1.c
fesub.o: fesub.c fedef.h
	 cc -c fesub.c
fe.o: fe.c fedef.h 
	 cc -c fe.c
fezoom.o: fezoom.c fedef.h
	cc -c fezoom.c
fewin.o: fewin.c fedef.h
	cc -c fewin.c
feshow.o: feshow.c fedef.h
	cc -c feshow.c
feprint.o: feprint.c fedef.h
	cc -c feprint.c
